# Generated by Django 4.1.4 on 2023-09-24 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_app_category_type_remove_profile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='file',
        ),
        migrations.RemoveField(
            model_name='app',
            name='type',
        ),
        migrations.AddField(
            model_name='app',
            name='types',
            field=models.ManyToManyField(related_name='apps', to='api.type'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='apps/images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='api.type')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='apps/files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='api.type')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='app',
            name='files',
            field=models.ManyToManyField(to='api.file'),
        ),
        migrations.AddField(
            model_name='app',
            name='images',
            field=models.ManyToManyField(to='api.image'),
        ),
    ]
