# Generated by Django 4.1.4 on 2023-09-24 07:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_app_files_alter_app_images_alter_app_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
