# Generated by Django 4.1.4 on 2023-09-24 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_app_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='api.profile'),
        ),
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='apps/icons/'),
        ),
    ]
