# Generated by Django 4.1.4 on 2023-09-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_app_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('reply', models.TextField(verbose_name='Reply')),
                ('star', models.PositiveIntegerField(default=5, verbose_name='Star Rating')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.app')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
