# Generated by Django 4.1.4 on 2023-09-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_category_options_alter_comment_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name']},
        ),
    ]
