# Generated by Django 4.1.4 on 2023-09-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_options_alter_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/images/'),
        ),
    ]
