# Generated by Django 4.1.4 on 2023-09-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pin',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Recovery Pin'),
        ),
    ]
