# Generated by Django 4.1.4 on 2023-09-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Recovery Pin'),
        ),
    ]
