# Generated by Django 4.1.4 on 2023-09-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_profile_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pin',
            field=models.CharField(blank=True, default='1234', max_length=4, verbose_name='Recovery Pin'),
        ),
    ]
