# Generated by Django 4.1.4 on 2023-09-29 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_profile_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Group Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Group Description')),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=100, verbose_name='Group Type')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/image/', verbose_name='Group image')),
                ('locked', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='groups_created', to='api.profile')),
                ('members', models.ManyToManyField(blank=True, related_name='groups_joined', to='api.profile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('file', models.FileField(blank=True, null=True, upload_to='groups/messages/files/', verbose_name='File messages')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='api.group')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='api.profile')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
