# Generated by Django 4.1.4 on 2023-09-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_group_groupchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_chat', to='api.group'),
        ),
    ]
