# Generated by Django 4.1.4 on 2023-09-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_groupchat_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100, null=True, verbose_name='Sender')),
                ('receiver', models.CharField(max_length=100, null=True, verbose_name='Receiver')),
                ('message', models.TextField(verbose_name='message')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('seen', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='last_message',
            field=models.TextField(blank=True, null=True, verbose_name='last message'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='seen_by',
            field=models.ManyToManyField(null=True, related_name='chats_seen', to='api.profile'),
        ),
    ]
