# Generated by Django 4.1.4 on 2023-09-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_chat_group_last_message_groupchat_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='seen_by',
            field=models.ManyToManyField(related_name='chats_seen', to='api.profile'),
        ),
    ]
