# Generated by Django 4.1.4 on 2023-09-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_groupchat_seen_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-updated']},
        ),
        migrations.AddField(
            model_name='group',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
