# Generated by Django 4.1.4 on 2023-09-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_chat_options_remove_chat_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='chats', to='api.profile'),
        ),
    ]
