# Generated by Django 4.1.4 on 2023-09-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_chatroom_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['date']},
        ),
    ]
