# Generated by Django 4.1.4 on 2023-09-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_chat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
