# Generated by Django 4.1.4 on 2023-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_profile_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seen_by',
            field=models.ManyToManyField(related_name='chat_seen', to='api.profile'),
        ),
    ]
