# Generated by Django 4.1.4 on 2023-09-30 11:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_chat_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=tinymce.models.HTMLField(null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='message',
            field=tinymce.models.HTMLField(null=True, verbose_name='message'),
        ),
    ]
