# Generated by Django 4.1.4 on 2023-09-30 11:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_chat_message_alter_groupchat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='last message'),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_message',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='last message'),
        ),
    ]
