# Generated by Django 4.1.4 on 2023-10-01 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_chatroom_last_message_alter_group_last_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active_friends', models.ManyToManyField(related_name='friends', to='api.profile')),
                ('blocked_friends', models.ManyToManyField(related_name='blocked_by', to='api.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_list', to='api.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
