# Generated by Django 4.1.4 on 2023-10-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_friend_active_friends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='file',
            new_name='files',
        ),
        migrations.AddField(
            model_name='chat',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='chats/messages/files/', verbose_name='File messages'),
        ),
        migrations.AddField(
            model_name='chat',
            name='starred_by',
            field=models.ManyToManyField(related_name='chat_starred', to='api.profile'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='starred_by',
            field=models.ManyToManyField(related_name='chats_starred', to='api.profile'),
        ),
    ]
