# Generated by Django 4.1.4 on 2023-10-02 14:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_file_groupchat_files_chat_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', tinymce.models.HTMLField(blank=True, null=True, verbose_name='status')),
                ('files', models.FileField(blank=True, null=True, upload_to='statuses/files/', verbose_name='File status')),
                ('background', models.CharField(max_length=50)),
                ('font_family', models.CharField(max_length=50)),
                ('font_weight', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('blocked_users', models.ManyToManyField(related_name='blocked_from', to='api.profile')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.profile')),
                ('viewed_by', models.ManyToManyField(related_name='status_viewed', to='api.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
