# Generated by Django 4.1.4 on 2023-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_from', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='status',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='status_viewed', to='api.profile'),
        ),
    ]
