# Generated by Django 4.1.4 on 2023-10-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_status_gotten_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='users/images/avatar.png', null=True, upload_to='users/images/'),
        ),
    ]
