# Generated by Django 4.1.4 on 2023-10-04 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='status_owner', to='api.status'),
        ),
    ]
