# Generated by Django 4.1.4 on 2023-10-04 11:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_friend_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='message',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='message'),
        ),
    ]
