# Generated by Django 4.1.4 on 2023-10-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_chat_message_alter_groupchat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='chat_starred', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='chats_starred', to='api.profile'),
        ),
    ]
