# Generated by Django 4.1.4 on 2023-10-06 18:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_chat_file_description_groupchat_file_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('All', 'All'), ('Appstore', 'Appstore'), ('iChat', 'iChat')], max_length=100, null=True, verbose_name='App')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('message', tinymce.models.HTMLField(blank=True, null=True, verbose_name='message')),
                ('active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seen_by', models.ManyToManyField(blank=True, related_name='read_notifications', to='api.profile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
