# Generated by Django 4.1.4 on 2023-10-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Success', 'Success'), ('Warning', 'Warning'), ('Congrats', 'Congrats'), ('Info', 'Info'), ('Danger', 'Danger')], max_length=100, null=True, verbose_name='Type'),
        ),
    ]
