# Generated by Django 4.1.4 on 2023-10-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='profile',
            name='openai_key',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='OpenAI API Key'),
        ),
    ]
