# Generated by Django 4.1.4 on 2023-12-21 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_address_author_dob_author_work_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='resume_project',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('job_title', models.CharField(blank=True, max_length=250)),
                ('company', models.CharField(blank=True, max_length=250)),
                ('phone_number', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='blog.author')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
