# Generated by Django 4.1.4 on 2023-12-21 17:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_project_resume_project_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='intro',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
