# Generated by Django 4.1.4 on 2023-12-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_notification_contact_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='star',
            field=models.PositiveIntegerField(default=5, verbose_name='Star Rating'),
        ),
    ]
