# Generated by Django 4.1.4 on 2023-12-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_active_comment_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
    ]
